### ISSUE TITLE
The 1st place is going to move five steps to the finishing line. The second place is going to move three steps toward the finishing line.  The third player is going to move one step towards the finish line.

### ISSUE THREAD

**Issue by so-ri** [sopra-fs23-group-28/sopra-fs23-group-28-server#40]

**Comment by samuelfrnk** [comment]
closed with commit: 
https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-server/commit/6f75c75e8a5814ec94ffa42d6914c7d3b6855f96

**Comment by samuelfrnk** [comment]
slightly changed to : 
1st : 3 steps 
2nd: 2 steps 
3rd: 1 step 
4th: -1 step
