### ISSUE TITLE
As client i want to be able to communicate with the backend through socketIO sockets in order to send and receive interactive messages

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs23-group-28/sopra-fs23-group-28-server#59]
- [x] #60
- [x] #61
- [x] #62
- [x] #63

**Comment by so-ri** [comment]
closed with commit(s) https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-server/commit/d8e874e5c85ff4e74bb081af5000ca57016b5035 https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-server/commit/50dcce5ed9ed6dd473171982c8caff66b1da6613 https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-server/commit/20342ba3cb1b5bbfeb1e21a3bb025aa9659d9b52
