### ISSUE TITLE
As developers we want to deploy our application to google cloud so that our clients can communicate in real time with each other

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs23-group-28/sopra-fs23-group-28-server#68]
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #73

**Comment by so-ri** [comment]
closed with the commits a1402b4d75402607a32208761fa95b6d2d8842d8 ab5747af84fef94886409b878fe622c490e1bb5a
